#!/bin/sh
### BEGIN INIT INFO
# Provides:              kismet
# Required-Start:     $all
# Required-Stop:     $local_fs $remote_fs $syslog $network
# Default-Start:         3 4 5
# Default-Stop:         0 1 6
# Short-Description:     Start kismet at boot time
# Description:         Starts kismet at boot time
### END INIT INFO
case "$1" in
start)
echo "Starting kismet"
/bin/sleep 30
/usr/local/bin/kismet_server --daemonize
;;
stop)
echo "Stopping kismet"
killall kismet_server
;;
*)
echo "Usage: /etc/init.d/kismet start|stop"
exit 1
;;
esac
exit 0
